// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hero.mywage.entity;

import com.hero.mywage.entity.AboutMeDataOnDemand;
import com.hero.mywage.entity.AboutMeIntegrationTest;
import com.hero.mywage.service.AboutMeService;
import java.math.BigInteger;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect AboutMeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AboutMeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AboutMeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    AboutMeDataOnDemand AboutMeIntegrationTest.dod;
    
    @Autowired
    AboutMeService AboutMeIntegrationTest.aboutMeService;
    
    @Test
    public void AboutMeIntegrationTest.testCountAllAboutMes() {
        Assert.assertNotNull("Data on demand for 'AboutMe' failed to initialize correctly", dod.getRandomAboutMe());
        long count = aboutMeService.countAllAboutMes();
        Assert.assertTrue("Counter for 'AboutMe' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AboutMeIntegrationTest.testFindAboutMe() {
        AboutMe obj = dod.getRandomAboutMe();
        Assert.assertNotNull("Data on demand for 'AboutMe' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AboutMe' failed to provide an identifier", id);
        obj = aboutMeService.findAboutMe(id);
        Assert.assertNotNull("Find method for 'AboutMe' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AboutMe' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AboutMeIntegrationTest.testFindAllAboutMes() {
        Assert.assertNotNull("Data on demand for 'AboutMe' failed to initialize correctly", dod.getRandomAboutMe());
        long count = aboutMeService.countAllAboutMes();
        Assert.assertTrue("Too expensive to perform a find all test for 'AboutMe', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AboutMe> result = aboutMeService.findAllAboutMes();
        Assert.assertNotNull("Find all method for 'AboutMe' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AboutMe' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AboutMeIntegrationTest.testFindAboutMeEntries() {
        Assert.assertNotNull("Data on demand for 'AboutMe' failed to initialize correctly", dod.getRandomAboutMe());
        long count = aboutMeService.countAllAboutMes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AboutMe> result = aboutMeService.findAboutMeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AboutMe' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AboutMe' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AboutMeIntegrationTest.testSaveAboutMe() {
        Assert.assertNotNull("Data on demand for 'AboutMe' failed to initialize correctly", dod.getRandomAboutMe());
        AboutMe obj = dod.getNewTransientAboutMe(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AboutMe' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AboutMe' identifier to be null", obj.getId());
        try {
            aboutMeService.saveAboutMe(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        Assert.assertNotNull("Expected 'AboutMe' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AboutMeIntegrationTest.testDeleteAboutMe() {
        AboutMe obj = dod.getRandomAboutMe();
        Assert.assertNotNull("Data on demand for 'AboutMe' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AboutMe' failed to provide an identifier", id);
        obj = aboutMeService.findAboutMe(id);
        aboutMeService.deleteAboutMe(obj);
        Assert.assertNull("Failed to remove 'AboutMe' with identifier '" + id + "'", aboutMeService.findAboutMe(id));
    }
    
}
