// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hero.mywage.entity;

import com.hero.mywage.entity.MyWebPageFileIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MyWebPageFileIntegrationTest_Roo_Configurable {
    
    declare @type: MyWebPageFileIntegrationTest: @Configurable;
    
}
