// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hero.mywage.entity;

import com.hero.mywage.entity.MyWebPageDataOnDemand;
import com.hero.mywage.entity.MyWebPageIntegrationTest;
import com.hero.mywage.service.MyWebPageService;
import java.math.BigInteger;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect MyWebPageIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MyWebPageIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MyWebPageIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    MyWebPageDataOnDemand MyWebPageIntegrationTest.dod;
    
    @Autowired
    MyWebPageService MyWebPageIntegrationTest.myWebPageService;
    
    @Test
    public void MyWebPageIntegrationTest.testCountAllMyWebPages() {
        Assert.assertNotNull("Data on demand for 'MyWebPage' failed to initialize correctly", dod.getRandomMyWebPage());
        long count = myWebPageService.countAllMyWebPages();
        Assert.assertTrue("Counter for 'MyWebPage' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MyWebPageIntegrationTest.testFindMyWebPage() {
        MyWebPage obj = dod.getRandomMyWebPage();
        Assert.assertNotNull("Data on demand for 'MyWebPage' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MyWebPage' failed to provide an identifier", id);
        obj = myWebPageService.findMyWebPage(id);
        Assert.assertNotNull("Find method for 'MyWebPage' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MyWebPage' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MyWebPageIntegrationTest.testFindAllMyWebPages() {
        Assert.assertNotNull("Data on demand for 'MyWebPage' failed to initialize correctly", dod.getRandomMyWebPage());
        long count = myWebPageService.countAllMyWebPages();
        Assert.assertTrue("Too expensive to perform a find all test for 'MyWebPage', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MyWebPage> result = myWebPageService.findAllMyWebPages();
        Assert.assertNotNull("Find all method for 'MyWebPage' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MyWebPage' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MyWebPageIntegrationTest.testFindMyWebPageEntries() {
        Assert.assertNotNull("Data on demand for 'MyWebPage' failed to initialize correctly", dod.getRandomMyWebPage());
        long count = myWebPageService.countAllMyWebPages();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MyWebPage> result = myWebPageService.findMyWebPageEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MyWebPage' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MyWebPage' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MyWebPageIntegrationTest.testSaveMyWebPage() {
        Assert.assertNotNull("Data on demand for 'MyWebPage' failed to initialize correctly", dod.getRandomMyWebPage());
        MyWebPage obj = dod.getNewTransientMyWebPage(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MyWebPage' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MyWebPage' identifier to be null", obj.getId());
        try {
            myWebPageService.saveMyWebPage(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        Assert.assertNotNull("Expected 'MyWebPage' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MyWebPageIntegrationTest.testDeleteMyWebPage() {
        MyWebPage obj = dod.getRandomMyWebPage();
        Assert.assertNotNull("Data on demand for 'MyWebPage' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MyWebPage' failed to provide an identifier", id);
        obj = myWebPageService.findMyWebPage(id);
        myWebPageService.deleteMyWebPage(obj);
        Assert.assertNull("Failed to remove 'MyWebPage' with identifier '" + id + "'", myWebPageService.findMyWebPage(id));
    }
    
}
