// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hero.mywage.entity;

import com.hero.mywage.entity.UserInfoDataOnDemand;
import com.hero.mywage.entity.UserInfoIntegrationTest;
import com.hero.mywage.service.UserInfoService;
import java.math.BigInteger;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect UserInfoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserInfoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserInfoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    UserInfoDataOnDemand UserInfoIntegrationTest.dod;
    
    @Autowired
    UserInfoService UserInfoIntegrationTest.userInfoService;
    
    @Test
    public void UserInfoIntegrationTest.testCountAllUserInfoes() {
        Assert.assertNotNull("Data on demand for 'UserInfo' failed to initialize correctly", dod.getRandomUserInfo());
        long count = userInfoService.countAllUserInfoes();
        Assert.assertTrue("Counter for 'UserInfo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserInfoIntegrationTest.testFindUserInfo() {
        UserInfo obj = dod.getRandomUserInfo();
        Assert.assertNotNull("Data on demand for 'UserInfo' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserInfo' failed to provide an identifier", id);
        obj = userInfoService.findUserInfo(id);
        Assert.assertNotNull("Find method for 'UserInfo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserInfo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UserInfoIntegrationTest.testFindAllUserInfoes() {
        Assert.assertNotNull("Data on demand for 'UserInfo' failed to initialize correctly", dod.getRandomUserInfo());
        long count = userInfoService.countAllUserInfoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserInfo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserInfo> result = userInfoService.findAllUserInfoes();
        Assert.assertNotNull("Find all method for 'UserInfo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserInfo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserInfoIntegrationTest.testFindUserInfoEntries() {
        Assert.assertNotNull("Data on demand for 'UserInfo' failed to initialize correctly", dod.getRandomUserInfo());
        long count = userInfoService.countAllUserInfoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserInfo> result = userInfoService.findUserInfoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserInfo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserInfo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserInfoIntegrationTest.testSaveUserInfo() {
        Assert.assertNotNull("Data on demand for 'UserInfo' failed to initialize correctly", dod.getRandomUserInfo());
        UserInfo obj = dod.getNewTransientUserInfo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserInfo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserInfo' identifier to be null", obj.getId());
        try {
            userInfoService.saveUserInfo(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        Assert.assertNotNull("Expected 'UserInfo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UserInfoIntegrationTest.testDeleteUserInfo() {
        UserInfo obj = dod.getRandomUserInfo();
        Assert.assertNotNull("Data on demand for 'UserInfo' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserInfo' failed to provide an identifier", id);
        obj = userInfoService.findUserInfo(id);
        userInfoService.deleteUserInfo(obj);
        Assert.assertNull("Failed to remove 'UserInfo' with identifier '" + id + "'", userInfoService.findUserInfo(id));
    }
    
}
